version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mozilor_test_project
    container_name: mozilor_test_project
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: 'laravel'
      MARIADB_USER: 'root'
      MARIADB_PASSWORD: 'root' 
      MARIADB_ROOT_PASSWORD: 'root' 
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
        PMA_HOST: 'db'
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: mozilor-nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:

volumes:
  dbdata:
